/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzBaseRelatedEntity } from './szBaseRelatedEntity';
import { SzAttributeSearchResultType } from './szAttributeSearchResultType';


/**
 * Describes an entity that matched attribute search criteria and how it matched against that criteria.
 */
export interface SzAttributeSearchResult extends SzBaseRelatedEntity { 
    // BEWARE!!! Added manually, autogen missed this property
    /** 
     * An enum string value describing the relationship type to the search criteria.
     * possible values: 'MATCH' | 'POSSIBLE_MATCH' | 'POSSIBLE_RELATION' | 'NAME_ONLY_MATCH'
     * 
    */
    resultType?: SzAttributeSearchResultType;

    /**
     * The integer \"match level\" describing how the related entity matched to the primary resolved entity.
     */
    matchLevel?: number;
    /**
     * The full name score between the primary resolved entity and this related entity.  The higher the score the closer the name match.
     */
    fullNameScore?: number;
    /**
     * The match score between the primary resolved entity and this related entity.  The higher the score the closer the match.
     */
    matchScore?: number;
    /**
     * A boolean flag indicating if this related entity represents a disclosed relationship.
     */
    disclosed?: boolean;
    /**
     * A boolean flag indicating if this related entity represents an ambiguous relationship.
     */
    ambiguous?: boolean;
    /**
     * The match key describing what features matched between the primary resolved entity and the related entity.
     */
    matchKey?: string;
    /**
     * The code identifying the resolution rule that related this entity to the primary resolved entity.
     */
    resolutionRuleCode?: string;
    /**
     * The ref score between the primary resolved entity and this related entity.
     */
    refScore?: number;
    /**
     * If true then this RelatedEntity has complete features and records, otherwise they are not provided.  Also, the recordSummary items will be missing the topRecordIds if partial is true.
     */
    partial?: boolean;
}