/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Enumerates the various classes of attribute types (and features). This is a generalization over attribute type that is more general than feature type (NOTE: stand-alone attribute types such as \"DATA_SOURCE\" or \"RECORD_ID\" do not have a feature type, but do have an attribute class of \"OBSERVATION\").  Attribute class determines how attributes / features are grouped together (e.g.: \"nameData\" contains all name features and \"identifierData\" contains all identifier features).  The possible values are:   * `ADDRESS` - Attributes pertaining to an address such as \"POSTAL_CODE\"   * `CHARACTERISTIC` - Attributes pertaining to physical characteristics                        of an entity.  Such as \"BIRTH_DATE\"   * `IDENTIFIER` - Attributes pertaining to identifiers such as                   drivers license number, passport number, or email                   address.   * `NAME` - Attributes pertaing to names such as \"NAME_FIRST\" or              \"NAME_LAST\"   * `OBSERVATION` - Attributes pertaining to meta-data about the                     observation (record) such as \"RECORD_ID\" or                     \"DATA_SOURCE\"   * `PHONE` - Attributes pertaining to phone numbers such               \"PHONE_NUMBER\" or \"PHONE_EXTENSION\"   * `RELATIONSHIP` - Attributes pertaining to relationships such as                      \"RELATIONSHIP_TYPE\".   * `OTHER` - An attribute class for custom features or for attributes               that are loaded but not mapped.
 */
export type SzAttributeClass = 'ADDRESS' | 'CHARACTERISTIC' | 'IDENTIFIER' | 'NAME' | 'OBSERVATION' | 'PHONE' | 'RELATIONSHIP' | 'OTHER';

export const SzAttributeClass = {
    ADDRESS: 'ADDRESS' as SzAttributeClass,
    CHARACTERISTIC: 'CHARACTERISTIC' as SzAttributeClass,
    IDENTIFIER: 'IDENTIFIER' as SzAttributeClass,
    NAME: 'NAME' as SzAttributeClass,
    OBSERVATION: 'OBSERVATION' as SzAttributeClass,
    PHONE: 'PHONE' as SzAttributeClass,
    RELATIONSHIP: 'RELATIONSHIP' as SzAttributeClass,
    OTHER: 'OTHER' as SzAttributeClass
};
