/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes how the entity matching the search attributes would have entity resolved against those attributes (either a match, possible match, discovered relationship or name only match).
 */
export type SzAttributeSearchResultType = 'MATCH' | 'POSSIBLE_MATCH' | 'POSSIBLE_RELATION' | 'NAME_ONLY_MATCH';

export const SzAttributeSearchResultType = {
    MATCH: 'MATCH' as SzAttributeSearchResultType,
    POSSIBLEMATCH: 'POSSIBLE_MATCH' as SzAttributeSearchResultType,
    POSSIBLERELATION: 'POSSIBLE_RELATION' as SzAttributeSearchResultType,
    NAMEONLYMATCH: 'NAME_ONLY_MATCH' as SzAttributeSearchResultType
};