/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzAttributeSearchResultType } from './szAttributeSearchResultType';
import { SzBaseRelatedEntity } from './szBaseRelatedEntity';
import { SzRelatedEntity } from './szRelatedEntity';

/**
 * Describes an entity that matched attribute search criteria and how it matched against that criteria.
 */
export interface SzAttributeSearchResult extends SzBaseRelatedEntity {
  resultType?: SzAttributeSearchResultType;
  /**
   * The array of RelatedEntity instances describing the possible matches, discovered relationships, and disclosed relationships.
   */
  relatedEntities?: Array<SzRelatedEntity>;
}
