/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SzBaseResponseMeta { 
    /**
     * The HTTP method that was used for the operation.
     */
    httpMethod?: SzBaseResponseMeta.HttpMethodEnum;
    /**
     * The HTTP status response code.
     */
    httpStatusCode?: number;
    /**
     * The timestamp of the operation's execution.
     */
    timestamp?: Date;
    version?: string;
    restApiVersion?: string;
    /**
     * The timing measurements that were taken where the keys are identifying what was timed and the values are the number of milliseconds.
     */
    timings?: { [key: string]: number; };
}
export namespace SzBaseResponseMeta {
    export type HttpMethodEnum = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
    export const HttpMethodEnum = {
        GET: 'GET' as HttpMethodEnum,
        POST: 'POST' as HttpMethodEnum,
        PUT: 'PUT' as HttpMethodEnum,
        PATCH: 'PATCH' as HttpMethodEnum,
        DELETE: 'DELETE' as HttpMethodEnum
    };
}