/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzDataSourceRecordAnalysis } from './szDataSourceRecordAnalysis';

/**
 * Describes the analysis performed against a set of bulk data records described as a JSON array, JSON Lines format or CSV format.
 */
export interface SzBulkDataAnalysis { 
    /**
     * The character encoding used to process the bulk data.
     */
    characterEncoding?: string;
    /**
     * The media type of the bulk data.
     */
    mediaType?: string;
    /**
     * The number of records found in the bulk data.  This may not match the number of \"observed entities\" once loaded since some records may be exact duplicates.
     */
    recordCount?: number;
    /**
     * The number of records provided that include a `RECORD_ID` value.
     */
    recordsWithRecordIdCount?: number;
    /**
     * The number of records provided that include a `DATA_SOURCE` value.
     */
    recordsWithDataSourceCount?: number;
    /**
     * The array of `SzDataSourceRecordAnalysis` elements map of string data source names to integer counts of how many records are provided with that data source name.
     */
    analysisByDataSource?: Array<SzDataSourceRecordAnalysis>;
}