/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzError } from './szError';

/**
 * Describes an error and the number of times it occurred.
 */
export interface SzBulkLoadError { 
    error?: SzError;
    /**
     * The number of times the error occurred while loading data from the bulk data set.
     */
    occurrenceCount?: number;
}