/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the status of a bulk load:   * `NOT_STARTED` - The bulk load has not started.   * `IN_PROGRESS` - If bulk load is in progress.   * `ABORTED` - The bulk load was aborted.   * `COMPLETED` - The bulk load completed without aborting.
 */
export type SzBulkLoadStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'ABORTED' | 'COMPLETED';

export const SzBulkLoadStatus = {
    NOTSTARTED: 'NOT_STARTED' as SzBulkLoadStatus,
    INPROGRESS: 'IN_PROGRESS' as SzBulkLoadStatus,
    ABORTED: 'ABORTED' as SzBulkLoadStatus,
    COMPLETED: 'COMPLETED' as SzBulkLoadStatus
};