/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes a data source.
 */
export interface SzDataSource { 
    /**
     * The data source code.
     */
    dataSourceCode?: string;
    /**
     * The data source ID. The value can be null when used for input in creating a data source to indicate that the data source ID should be auto-generated.
     */
    dataSourceId?: number;
}