/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzBulkLoadError } from './szBulkLoadError';

/**
 * Provides statistics specific to a given data source of the records loaded from bulk data.
 */
export interface SzDataSourceBulkLoadResult { 
    /**
     * The data source code identifying the data source for which the load statistics are being provided.  This is `null` if the statistics pertain to those records with no data source defined in the source data.
     */
    dataSource?: string;
    /**
     * The number of records found in the bulk data set having the associated data source.  This may not match the number of \"observed entities\" once loaded since some records may be exact duplicates.
     */
    recordCount?: number;
    /**
     * The number of records successfully loaded from the bulk data set having the associated data source.  This may not match the number of \"observed entities\" loaded for that data source since some records may be exact duplicates.
     */
    loadedRecordCount?: number;
    /**
     * The number of records from the bulk data set having the associated data source that failed to load.
     */
    failedRecordCount?: number;
    /**
     * The array of top error occurrences with the number of times they occurred when loading records with the associated data source.
     */
    topErrors?: Array<SzBulkLoadError>;
}