/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Identifies zero or more entities by either its entity ID or by the data source code and record ID of one of their constituent records. Identifiers in the array are homogeneous, either all entity IDs or all RecordId instances containing the data-source-code/record-id pair.
 */
export interface SzEntityIdentifiers { 
}