/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave the similarly to its stand operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes a record (aka: observed entity) that has been loaded for a particular data source.
 */
export interface SzEntityRecord {
    /**
     * The data source code identifying the source from which the record was loaded.
     */
    dataSource?: string;
    /**
     * The identifier that uniquely identifies this record from other records from the same data source.  This may have been loaded with the record or automatically generated from the record's data.
     */
    recordId?: string;
    /**
     * An array of addresses associated with the record that are formatted for readability.  These may be prefixed by a \"usage type\" if one was provided (e.g.: \"HOME: 101 Main Street\")
     */
    addressData?: Array<string>;
    /**
     * An array of characteristics associated with the record that are formatted for readability.  These will be prefixed by a characteristic type and optionally by a \"usage type\" if one was provided.
     */
    characteristicData?: Array<string>;
    /**
     * An array of entity data associated with the record where the items are formatted for readability.  These will be prefixed by an identifier type and may be prefixed by a \"usage type\" if one was provided (e.g.: \"ID: 123456789\" or \"EMAIL: WORK: joe@nowhere.com\")
     */
    identifierData?: Array<string>;
    /**
     * An array of names associated with the record that are formatted for readability.  These may be prefixed by a \"usage type\" if one was provided (e.g.: \"Joe Schmoe\" or \"AKA: Joseph P. Schmoe\")
     */
    nameData?: Array<string>;
    /**
     * An array of phone numbers associated with the record that are formatted for readability.  These may be prefixed by a \"usage type\" if one was provided (e.g.: \"HOME: 702-555-1212\")
     */
    phoneData?: Array<string>;
    /**
     * An array of relationship data items associated with the record that describes disclosed relationships.
     */
    relationshipData?: Array<string>;
    /**
     * An array of associated data items that were loaded with the record but not normally recognized or used for entity resolution.  This array usually contains useful information from the source system.
     */
    otherData?: Array<string>;
    /**
     * The JSON representation of the original data record that was loaded.
     */
    originalSourceData?: { [key: string]: any; };
}
