/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave the similarly to its stand operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzEntityFeatureDetail } from './szEntityFeatureDetail';

/**
 * Describes a feature for an entity as well as including any close values for the feature that were considered to be duplicate values for entity resolution purposes.
 */
export interface SzEntityFeature {
    /**
     * The internal ID for the primary feature value.
     */
    primaryId?: number;
    /**
     * The primary value for the feature.
     */
    primaryValue?: string;
    /**
     * The optional associated usage type (e.g.: \"HOME\" or \"WORK\")
     */
    usageType?: string;
    /**
     * The array of values that are close enough to the primary value for the feature that they are considered to be duplicate values for the purpose of entity resolution.
     */
    duplicateValues?: Array<string>;
    /**
     * The array of `SzEntityFeatureDetail` instances describing the each of the clustered feature values in detail.
     */
    featureDetails?: Array<SzEntityFeatureDetail>;
}
