/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes a feature for an entity as well as including any close values for the feature that were considered to be duplicate values for entity resolution purposes.
 */
export interface SzEntityFeature { 
    primaryValue?: string;
    /**
     * The optional associated usage type (e.g.: \"HOME\" or \"WORK\")
     */
    usageType?: string;
    /**
     * The array of values that are close enough to the primary value for the feature that they are considered to be duplicate values for the purpose of entity resolution.
     */
    duplicateValues?: Array<string>;
}