/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes an entity type.
 */
export interface SzEntityType { 
    /**
     * The entity type code.
     */
    entityTypeCode?: string;
    /**
     * The entity class code associated with the entity type.
     */
    entityClassCode?: string;
    /**
     * The entity type ID.  The value can be null when used for input in creating an entity type to indicate that the entity type ID should be auto-generated.
     */
    entityTypeId?: number;
}