/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave the similarly to its stand operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the various match levels describing how two records resolve against each other.  The possible values are:   * `NO_MATCH` - No match was found between the records.   * `RESOLVED` - The records resolved to the same entity.   * `POSSIBLY_SAME` - The records were not close enough to resolve     but may represent the same entity if more data was provided.   * `POSSIBLY_RELATED` - The records share some attributes that     suggest a relationship.   * `NAME_ONLY` - The records match in name only.   * `DISCLOSED` - An explicit relationship has been disclosed between     the records.
 */
export type SzMatchLevel = 'NO_MATCH' | 'RESOLVED' | 'POSSIBLY_SAME' | 'POSSIBLY_RELATED' | 'NAME_ONLY' | 'DISCLOSED';

export const SzMatchLevel = {
    NOMATCH: 'NO_MATCH' as SzMatchLevel,
    RESOLVED: 'RESOLVED' as SzMatchLevel,
    POSSIBLYSAME: 'POSSIBLY_SAME' as SzMatchLevel,
    POSSIBLYRELATED: 'POSSIBLY_RELATED' as SzMatchLevel,
    NAMEONLY: 'NAME_ONLY' as SzMatchLevel,
    DISCLOSED: 'DISCLOSED' as SzMatchLevel
};