/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave the similarly to its stand operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzBaseRelatedEntity } from './szBaseRelatedEntity';
import { SzRelationshipType } from './szRelationshipType';
import { SzEntityFeature } from './szEntityFeature';

/**
 * Provides a description of an entity that is related to a ResolvedEntity.  This describes how the entity is related and may be missing the complete features and record list of a ResolvedEntity.
 */
export interface SzRelatedEntity extends SzBaseRelatedEntity {
    // BEWARE!!! Added manually, autogen missed this property
    /**
     * An enum string value describing the relationship type to the entity.
     * possible values: 'POSSIBLE_MATCH' | 'POSSIBLE_RELATION' | 'DISCLOSED_RELATION'
     *
    */
    relationType?: SzRelationshipType;

    /**
     * The integer \"match level\" describing how the related entity matched to the primary resolved entity.
     */
    matchLevel?: number;
    /**
     * The full name score between the primary resolved entity and this related entity.  The higher the score the closer the name match.
     */
    fullNameScore?: number;
    /**
     * The match score between the primary resolved entity and this related entity.  The higher the score the closer the match.
     */
    matchScore?: number;
    /**
     * A boolean flag indicating if this related entity represents a disclosed relationship.
     */
    disclosed?: boolean;
    /**
     * A boolean flag indicating if this related entity represents an ambiguous relationship.
     */
    ambiguous?: boolean;
    /**
     * The match key describing what features matched between the primary resolved entity and the related entity.
     */
    matchKey?: string;
    /**
     * The code identifying the resolution rule that related this entity to the primary resolved entity.
     */
    resolutionRuleCode?: string;
    /**
     * The ref score between the primary resolved entity and this related entity.
     */
    refScore?: number;
}
