/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave the similarly to its stand operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SzScoringFrequency } from './szScoringFrequency';

/**
 * Describes the scoring behavior for a feature / feature type.
 */
export interface SzScoringBehavior {
    /**
     * The code identifying the behavior.
     */
    code?: string;
    frequency?: SzScoringFrequency;
    /**
     * `true` if an entity should typically have only one value for a feature of this type (like a Social Security Number, Date of Birth) and `false` if the entity can typically have multiple values for the feature type (like Address or Phone Number).  This value is `null` if exclusivity is not applicable to the scoring behavior such as with special scoring behaviors like `NAME`.
     */
    exclusive?: boolean;
    /**
     * `true` if the feature value for the feature type remains constant for an entity over time (like a Date of Birth), and `false` if it can can change for the entity over time (like a Home Address).  This is `null` if the stability is not applicable to the scoring behavior such as with special behaviors like `NAME`.
     */
    stable?: boolean;
}
