/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave the similarly to its stand operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Provides information about which server features are enabled and which are not enabled.
 */
export interface SzServerInfo {
  /**
   * The number of Senzing worker threads pooled for handling requests.
   */
  concurrency?: number;
  /**
   * The active configuration ID being used by the API server.  This is still available if the server was started with a static file configuration via the `G2CONFIGFILE` initialization property.
   */
  activeConfigId?: number;
  /**
   * Whether or not the server will automatically pickup the latest default configuration if it changes.
   */
  dynamicConfig?: boolean;
  /**
   * Whether or not the server was started in read-only mode.  If in read-only mode then operations that modify the repository (e.g.: loading records or configuring new data sources) are not allowed.
   */
  readOnly?: boolean;
  /**
   * Whether or not admin features are enabled.  If admin features are not enabled then the configuration cannot be modified.
   */
  adminEnabled?: boolean;
}
