/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com)
 *
 * OpenAPI spec version: 1.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the Senzing version information.
 */
export interface SzVersionInfo { 
    /**
     * The version of the REST API Server implementation.
     */
    apiServerVersion?: string;
    /**
     * The version of the REST API Specification that is implemented.
     */
    restApiVersion?: string;
    /**
     * The version for the underlying runtime native Senzing API.
     */
    nativeApiVersion?: string;
    /**
     * The build number for the underlying runtime native Senzing API.
     */
    nativeApiBuildNumber?: string;
    /**
     * The build date for the underlying runtime native Senzing API.
     */
    nativeApiBuildDate?: Date;
    /**
     * The configuration compatibility version for the underlying runtime native Senzing API.
     */
    configCompatibilityVersion?: string;
}